import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "UsersLayout metadata",
    description: "Generated by UsersLayout metadata",
}
type Props = { children: React.ReactNode }
const UsersLayout = ({children}: Props) => {
    return (
        <>
            {children}
        </>
    );
};

export default UsersLayout;