import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "CommentLayout metadata",
    description: "Generated by CommentLayout metadata",
}
type Props = { children: React.ReactNode }
const CommentLayout = ({children}: Props) => {
    return (
        <>
            {children}
        </>
    );
};

export default CommentLayout;