import type { Metadata } from "next";
import Menu from "@/Menu";


export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Menu/>
      {children}
      </body>
    </html>
  );
}
