import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "PostsLayout metadata",
    description: "Generated by PostsLayout metadata",
}
type Props = { children: React.ReactNode }
const PostsLayout = ({children}: Props) => {
    return (
        <>
            {children}
        </>
    );
};

export default PostsLayout;